# Generated by Django 5.1.1 on 2024-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('area', models.IntegerField()),
                ('open_t', models.IntegerField()),
                ('close_t', models.IntegerField()),
            ],
        ),
    ]
